name: Ramn-Web CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "TAGPLZ=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build ./src/Ramn.Web.MVC --tag ramn-web:$TAGPLZ
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Push the Docker image
      run: docker push ramn-web:$TAGPLZ
